# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 16:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0002_auto_20170324_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favQuotes', to='exam_app.Quote'),
        ),
    ]
